//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_app
    {
        public int job_id { get; set; }
        public int user_id { get; set; }
        public int comp_id { get; set; }
        public string resume { get; set; }
        public System.DateTime date { get; set; }
    }
}
