//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//--
//----------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace mvcproject.Models
{
   
    public class JobSearch
    {
        public JobSearch()
        {
            selectjob = new List<job_1>();
            insertse = new job_1();
        }

        public job_1 insertse { set; get; }
        public List<job_1> selectjob { set; get; }
    }


    public  class job_1
    {
        public int job_id { get; set; }
        public int comp_id { get; set; }
        public string job_title { get; set; }
        public string job_description { get; set; }
        public decimal salary { get; set; }
        public string location { get; set; }
        public string experience { get; set; }
        public string skills { get; set; }
        public string job_type { get; set; }
        public string _job_status { get; set; }
        public string job_status
        {
            get
            {
                if (DateTime.Now > end_date)
                {
                    return "Closed";
                }
                return _job_status;
            }
            set
            {
                _job_status = value;
            }
        }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    }
}
