//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_reg
    {
        public int user_id { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public long phone { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string qualification { get; set; }
        public string experience { get; set; }
        public string skills { get; set; }
        public string resume { get; set; }
        public string photo { get; set; }
        public string current_location { get; set; }
    }
}
